apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  selector:
    role: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
